# Copyright 2020-2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: attenuation
version: 0.1.0.0
category: Constraints
synopsis: Representational subtyping relations and variance roles.
description: |
  This lets you coerce containers (among other things) from stronger types to
  weaker types with zero runtime cost when it's safe to do so, e.g.
  @[Fin n] -> [Int]@.  This primarily comes into play when using newtypes to
  impose additional invariants on existing types.
license: Apache-2.0
author: Andrew Pritchard <awpr@google.com>
copyright: 2020-2021 Google LLC
maintainer: Andrew Pritchard <awpr@google.com>
github: google/hs-attenuation

# Note: this causes CHANGELOG.md to be included in Hackage distributions.
extra-source-files:
  CHANGELOG.md

dependencies:
  - base >= 4.7 && < 4.16
  - profunctors >= 0.1 && < 5.7

library:
  source-dirs: src
  exposed-modules:
    - Data.Type.Attenuation
